name: Build

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Install packages
        run: |
          sudo apt update
          sudo apt install -y -o Acquire::Retries=50 \
                           binutils-dev libiberty-dev zlib1g-dev python-is-python3 zip
      - name: Build NTloader
        run: |
          make
      - name: Create package
        run: ./makepkg.sh
      - name: Release
        continue-on-error: true
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          gh release delete latest --cleanup-tag --yes
          gh release create latest ntloader.zip -t "Development Build" -p
        env:
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
